# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baron_match_report',
            name='did_blue_win',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='game_number',
            field=models.PositiveIntegerField(help_text='Should be the true game number for the entire season, not week number'),
        ),
    ]
