# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=64)),
                ('summoner_id', models.PositiveIntegerField()),
                ('discord_name', models.CharField(max_length=30)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('who_added_person', models.CharField(max_length=64)),
                ('reason_for_ban', models.CharField(choices=[('Account sharing', 'Account sharing'), ('Smurfing', 'Smurfing'), ('Toxic', 'Toxic'), ('Other', 'Other')], max_length=20)),
                ('supporting_documentation', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bad Accounts',
                'db_table': 'Bad Accounts',
            },
        ),
    ]
