# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baron_league',
            options={'verbose_name_plural': 'Baron League'},
        ),
        migrations.AlterModelOptions(
            name='baron_post',
            options={'verbose_name_plural': 'Baron News'},
        ),
        migrations.AlterModelOptions(
            name='baron_standings',
            options={'verbose_name_plural': 'Baron League Standings'},
        ),
        migrations.AlterModelOptions(
            name='baron_team_sign_ups',
            options={'verbose_name_plural': 'Baron Sign Ups'},
        ),
        migrations.AlterModelOptions(
            name='dragon_league',
            options={'verbose_name_plural': 'Dragon League'},
        ),
        migrations.AlterModelOptions(
            name='dragon_post',
            options={'verbose_name_plural': 'Dragon News'},
        ),
        migrations.AlterModelOptions(
            name='dragon_solo_sign_ups',
            options={'verbose_name_plural': 'Dragon Solo Sign Ups'},
        ),
        migrations.AlterModelOptions(
            name='dragon_standings',
            options={'verbose_name_plural': 'Dragon League Standings'},
        ),
        migrations.AlterModelOptions(
            name='elder_league',
            options={'verbose_name_plural': 'Elder League'},
        ),
        migrations.AlterModelOptions(
            name='elder_post',
            options={'verbose_name_plural': 'Elder News'},
        ),
        migrations.AlterModelOptions(
            name='elder_solo_sign_ups',
            options={'verbose_name_plural': 'Elder Solo Sign Ups'},
        ),
        migrations.AlterModelOptions(
            name='elder_standings',
            options={'verbose_name_plural': 'Elder League Standings'},
        ),
        migrations.AlterModelOptions(
            name='elder_team_sign_ups',
            options={'verbose_name_plural': 'Elder Team Sign Ups'},
        ),
    ]
