# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0002_badaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badaccounts',
            name='reason_for_ban',
            field=models.CharField(choices=[('Account sharing inside League Play', 'Account sharing inside League Play'), ('Account sharing outside League Play', 'Account sharing outisde League Play'), ('Smurfing', 'Smurfing'), ('Toxic', 'Toxic'), ('Other', 'Other')], max_length=20),
        ),
    ]
