# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0003_auto_20180722_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dragon_Standings',
        ),
        migrations.DeleteModel(
            name='Elder_Standings',
        ),
    ]
