# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0004_auto_20180722_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baron_match_report',
            name='blue_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_team', to='AscensionESports_Baseline.Baron_League_Rosters'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='red_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_team', to='AscensionESports_Baseline.Baron_League_Rosters'),
        ),
    ]
