# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0005_auto_20180722_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baron_standings',
            name='team_name',
        ),
        migrations.DeleteModel(
            name='Baron_Standings',
        ),
    ]
