# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-16 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0006_dragon_team_sign_ups'),
    ]

    operations = [
        migrations.AddField(
            model_name='baron_players',
            name='alt_names',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='baron_players',
            name='previous_ign',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='dragon_players',
            name='alt_names',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='dragon_players',
            name='previous_ign',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='elder_players',
            name='alt_names',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='elder_players',
            name='previous_ign',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
