# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0006_auto_20180722_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='baron_match_report',
            name='week_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='did_blue_win',
            field=models.BooleanField(default=True, help_text='DOUBLE CHECK THIS'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='game_number',
            field=models.PositiveIntegerField(help_text="In BoX series, it's game number. Otherwise, game number for a given week"),
        ),
    ]
