# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0007_auto_20180722_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baron_match_report',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
