# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0008_auto_20180722_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baron_players',
            old_name='first_blood',
            new_name='first_bloods',
        ),
        migrations.AddField(
            model_name='baron_players',
            name='avg_csd_at_ten',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baron_players',
            name='avg_damage_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baron_players',
            name='csd_at_ten',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baron_players',
            name='damage_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baron_players',
            name='first_tower',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
