# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-06 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0010_auto_20180722_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='League_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(default='Dragon League X', max_length=50)),
                ('league', models.CharField(choices=[('Dragon', 'Dragon'), ('Elder', 'Elder'), ('Baron', 'Baron')], max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('week_length', models.PositiveIntegerField(choices=[(5, 5), (9, 9)], default=9)),
                ('regular_season_schedule', models.PositiveIntegerField(choices=[('Bo1', 1), ('Bo2', 2), ('Bo3', 3)], default=1)),
                ('number_of_teams', models.PositiveIntegerField(default=10, help_text='This is always assumed to be 10')),
                ('pools', models.PositiveIntegerField(default=1, help_text='In case we got multiple Elder Leagues again')),
            ],
        ),
        migrations.AddField(
            model_name='baron_league',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This will change to false whenever the League is over.'),
        ),
        migrations.AddField(
            model_name='baron_league_rosters',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This will change to false whenever the League is over.'),
        ),
        migrations.AddField(
            model_name='baron_team_sign_ups',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This will change to false whenever the League is over.'),
        ),
        migrations.AddField(
            model_name='dragon_league',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This will change to false whenever the League is over.'),
        ),
        migrations.AddField(
            model_name='elder_league',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This will change to false whenever the League is over.'),
        ),
        migrations.AddField(
            model_name='elder_team_sign_ups',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This will change to false whenever the League is over.'),
        ),
    ]
