# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0011_auto_20190106_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_track',
            name='regular_season_schedule',
            field=models.PositiveIntegerField(choices=[(1, 'Bo1'), (2, 'Bo2'), (3, 'Bo3')], default=1),
        ),
    ]
