# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-06 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0012_auto_20190106_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league_track',
            options={'verbose_name_plural': 'League Tracker'},
        ),
        migrations.AlterModelTable(
            name='league_track',
            table='League Tracker',
        ),
    ]
