# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-07 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0013_auto_20190106_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder_solo_sign_ups',
            name='duo_partner',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
