# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0014_elder_solo_sign_ups_duo_partner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='League_Track',
            new_name='Start_League',
        ),
        migrations.AddField(
            model_name='baron_match_report',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
