# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0015_auto_20190203_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_league',
            name='start_date',
            field=models.DateField(),
        ),
    ]
