# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0016_auto_20190203_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baron_league',
            name='team_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='baron_league_rosters',
            name='team_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='match_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baron_team_sign_ups',
            name='team_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dragon_league',
            name='team_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='elder_league',
            name='team_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='elder_team_sign_ups',
            name='team_name',
            field=models.CharField(max_length=25),
        ),
    ]
