# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-03 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0017_auto_20190203_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='start_league',
            options={'verbose_name_plural': 'Start League'},
        ),
        migrations.AlterModelTable(
            name='start_league',
            table='Start League',
        ),
    ]
