# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-09 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0020_auto_20190209_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baron_match_report',
            name='blue_ad_carry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_ad_carry', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='blue_jungler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_jungler', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='blue_mid_laner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_mid_laner', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='blue_support',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_support', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='blue_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_team', to='AscensionESports_Baseline.Baron_League_Rosters'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='blue_top_laner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_top_laner', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='red_ad_carry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_ad_carry', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='red_jungler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_jungler', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='red_mid_laner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_mid_laner', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='red_support',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_support', to='AscensionESports_Baseline.Baron_Players'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='red_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_team', to='AscensionESports_Baseline.Baron_League_Rosters'),
        ),
        migrations.AlterField(
            model_name='baron_match_report',
            name='red_top_laner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_top_laner', to='AscensionESports_Baseline.Baron_Players'),
        ),
    ]
