# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-10 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AscensionESports_Baseline', '0021_auto_20190209_1748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baron_match_report',
            unique_together=set([('blue_team', 'red_team', 'date')]),
        ),
    ]
